# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86821735f937ba753c48e4930f9f16f7aa65e178bdb21c32e1581d5e026e7e65c3a6dfe1f12feb9d19e2577eb677a86c27eebe93416012ba7adfef84d306f67a

test:
  secret_key_base: eaba01f4698c9d4d2ba606dd9fbfc3e09b90883f6ff151670c4c10cbe12966c2b296432335f10ddfc8ab7981ffcd522f6255457ceebbd9334dcebaea9249eaac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
